### ISSUE TITLE
Riddle megoldási paraméterek

### ISSUE THREAD

**Issue by kiskoza** [janosgats/laboschqpa.server#1]
Hello. A [kódban](https://github.com/janosgats/laboschqpa.server/blob/913b8ede88b0daeb60b2b763a9f03fd980983f68/src/main/java/com/laboschqpa/server/api/service/RiddleService.java#L87) láttam, hogy a jelenlegi riddle szabályzat a kis és nagy betűket nem különbözteti meg, azonban az ékezeteket, írásjeleket és whitespace-eket benne hagyja, ezzel nagyban megnehezítve a kellemes kikapcsolódást.

Van-e lehetőség ezen változtatni? Amennyiben fogadtok PR-okat, szívesen ~berakok egy backdoort~ segítek benne.

**Comment by janosgats** [comment]
Feljavítottam. Köszi a javaslatot!
